// แก้ไข app/api/cars/route.ts
import { NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Car from '@/models/Car';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

// POST - Create a new car
export async function POST(request: Request) {
  try {
    // Check authorization
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== 'admin') {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    await connectDB();
    
    // Parse request body
    const body = await request.json();
    console.log('Car creation request body:', body);
    
    const { car_name, car_capacity, car_registration, car_type, user_id } = body;
    
    // Validate required fields
    if (!car_name || !car_registration) {
      console.error('Car validation failed:', { car_name, car_registration });
      return NextResponse.json(
        { error: 'Car name and registration are required' },
        { status: 400 }
      );
    }
    
    // Set default capacity if not provided
    const capacity = car_capacity || 10;
    
    // Auto-generate car ID (format: CAR-YYMMDD-XXX)
    const date = new Date();
    const year = date.getFullYear().toString().slice(-2);
    const month = (date.getMonth() + 1).toString().padStart(2, '0');
    const day = date.getDate().toString().padStart(2, '0');
    
    // Find the last car to increment the counter
    const latestCar = await Car.findOne().sort({ car_id: -1 });
    let counter = 1;
    
    if (latestCar && latestCar.car_id) {
      const match = latestCar.car_id.match(/\d+$/);
      if (match) {
        counter = parseInt(match[0]) + 1;
      }
    }
    
    const counterStr = counter.toString().padStart(3, '0');
    const autoGeneratedCarId = `CAR-${year}${month}${day}-${counterStr}`;
    
    // Check if car with same registration already exists
    const existingCar = await Car.findOne({ car_registration });
    if (existingCar) {
      return NextResponse.json(
        { error: 'Car with this registration already exists' },
        { status: 409 }
      );
    }
    
    try {
      // Create car data object with auto-generated ID
      const carData = {
        car_id: autoGeneratedCarId,
        car_name,
        car_capacity: capacity,
        car_registration,
        car_type: car_type || 'van', // เพิ่ม default car_type
        user_id: user_id || null
      };
      
      console.log('Creating car with data:', carData);
      
      // Create car
      const newCar = await Car.create(carData);
      console.log('Car created successfully with ID:', autoGeneratedCarId);
      
      // ตรวจสอบให้แน่ใจว่า newCar มีข้อมูล ก่อนส่งกลับ
      if (!newCar) {
        return NextResponse.json(
          { error: 'Failed to create car but no error returned' },
          { status: 500 }
        );
      }
      
      return NextResponse.json(newCar);
    } catch (innerError) {
      console.error('Error during car creation process:', innerError);
      return NextResponse.json(
        { error: 'Error processing car data: ' + (innerError as Error).message },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error('Create Car Error:', error);
    return NextResponse.json(
      { error: 'Failed to create car: ' + (error as Error).message },
      { status: 500 }
    );
  }
}

// แก้ไข GET method ใน app/api/cars/route.ts

// GET - Get all cars
export async function GET(request: Request) {
  try {
    // Check authorization
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    await connectDB();
    
    // Get query parameters (optional)
    const { searchParams } = new URL(request.url);
    const driverId = searchParams.get('user_id');
    
    // Build query
    const query: any = {};
    if (driverId) {
      query.user_id = driverId;
    }
    
    try {
      // Find cars based on query
      const cars = await Car.find(query);
      
      if (!cars) {
        return NextResponse.json([], { status: 200 });
      }
      
      // พยายามทำ populate ให้กับ user_id ถ้าเป็นไปได้
      try {
        const populatedCars = await Car.find(query).populate({
          path: 'user_id',
          select: 'name email role employeeId phone checkInStatus'
        });
        
        return NextResponse.json(populatedCars);
      } catch (populateError) {
        console.warn('Failed to populate user data in cars, returning unpopulated cars:', populateError);
        return NextResponse.json(cars);
      }
    } catch (findError) {
      console.error('Error finding cars:', findError);
      return NextResponse.json(
        { error: 'Database error: ' + (findError as Error).message },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error('Get Cars Error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch cars: ' + (error as Error).message },
      { status: 500 }
    );
  }
}